import { useState } from "react";
import { jsPDF } from "jspdf";
import {
  BookOpen,
  Copy,
  Download,
  Sparkles,
} from "lucide-react";

import MainLayout from "../layouts/MainLayout";

function LiteratureSurvey() {

  const [loading, setLoading] = useState(false);
  const [report, setReport] = useState("");

  const generateLiteratureSurvey = async () => {

    setLoading(true);

    try {

      const response = await fetch(
        "http://127.0.0.1:5000/literature-survey"
      );

      const data = await response.json();

      if (data.success) {

        setReport(data.literature_survey);

      } else {

        alert(data.message || "Unable to generate report.");

      }

    } catch (error) {

      console.log(error);

      alert("Unable to connect to backend.");

    }

    setLoading(false);

  };

  const copyReport = () => {

    navigator.clipboard.writeText(report);

    alert("Literature Survey copied successfully.");

  };

const downloadReport = () => {

  if (!report) {

    alert("Please generate a report first.");
    return;

  }

  const pdf = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  const pageWidth = 210;
  const margin = 20;
  const maxWidth = 170;

  let y = 20;

  // Header
  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(22);
  pdf.text("ResearchMind AI", margin, y);

  y += 10;

  pdf.setFontSize(15);
  pdf.text("Literature Survey Report", margin, y);

  y += 8;

  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(10);
  pdf.text(
    `Generated On: ${new Date().toLocaleString()}`,
    margin,
    y
  );

  y += 6;

  pdf.line(margin, y, pageWidth - margin, y);

  y += 10;

  const lines = report.split("\n");

  lines.forEach((line) => {

    // New Page
    if (y > 275) {

      pdf.addPage();
      y = 20;

    }

    const text = line.trim();

    if (text === "") {

      y += 5;
      return;

    }

    // Main Heading (#)
    if (text.startsWith("# ")) {

      pdf.setFont("helvetica", "bold");
      pdf.setFontSize(18);

      pdf.text(
        text.replace("# ", ""),
        margin,
        y
      );

      y += 10;

      return;

    }

    // Section Heading (##)
    if (text.startsWith("## ")) {

      pdf.setFont("helvetica", "bold");
      pdf.setFontSize(15);

      pdf.text(
        text.replace("## ", ""),
        margin,
        y
      );

      y += 8;

      return;

    }

    // Sub Heading (###)
    if (text.startsWith("### ")) {

      pdf.setFont("helvetica", "bold");
      pdf.setFontSize(13);

      pdf.text(
        text.replace("### ", ""),
        margin,
        y
      );

      y += 7;

      return;

    }

    // Paragraph
    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(11);

    const paragraph = pdf.splitTextToSize(
      text,
      maxWidth
    );

    pdf.text(
      paragraph,
      margin,
      y
    );

    y += paragraph.length * 6 + 2;

  });

  pdf.setFontSize(9);

  pdf.setFont("helvetica", "italic");

  pdf.text(
    "Generated by ResearchMind AI",
    margin,
    290
  );

  pdf.save("LiteratureSurveyReport.pdf");

};
  return (

    <MainLayout>

      {/* Header */}

      <div className="flex items-center gap-5">

        <div
          className="
            rounded-2xl
            bg-[var(--button-bg)]
            p-4
          "
        >

          <BookOpen
            size={38}
            className="text-[var(--button-text)]"
          />

        </div>

        <div>

          <h1 className="text-4xl font-bold text-[var(--primary-text)]">

            Literature Survey Generator

          </h1>

          <p className="mt-2 text-[var(--secondary-text)]">

            Generate a professional academic literature
            survey from all uploaded research papers.

          </p>

        </div>

      </div>

      {/* Generate Button */}

      <div className="mt-10">

        <button
          onClick={generateLiteratureSurvey}
          disabled={loading}
          className="
            flex
            items-center
            gap-3
            rounded-xl
            bg-[var(--button-bg)]
            px-7
            py-3
            font-semibold
            text-[var(--button-text)]
            transition
            hover:opacity-90
            disabled:opacity-50
          "
        >

          <Sparkles size={18} />

          {loading
            ? "Generating Literature Survey..."
            : "Generate Literature Survey"}

        </button>

      </div>

      {/* Loading */}

      {loading && (

        <div
          className="
            mt-8
            rounded-2xl
            border
            border-[var(--border-color)]
            bg-[var(--card-bg)]
            p-8
          "
        >

          <p className="text-lg font-medium">

            AI is generating your Literature Survey...

          </p>

          <p className="mt-3 text-[var(--secondary-text)]">

            Analyzing all uploaded papers,
            identifying research trends,
            comparing methodologies,
            and generating a professional
            literature survey.

          </p>

        </div>

      )}

      {/* Report */}

      {!loading && report && (

        <div
          className="
            mt-10
            rounded-2xl
            border
            border-[var(--border-color)]
            bg-[var(--card-bg)]
            p-8
          "
        >

          <div className="mb-8 flex items-center justify-between">

            <div>

              <h2 className="text-2xl font-bold">

                AI Literature Survey

              </h2>

              <p className="mt-2 text-sm text-[var(--secondary-text)]">

                Generated from all uploaded research papers.

              </p>

            </div>

            <div className="flex gap-3">

              <button
                onClick={copyReport}
                className="
                  flex
                  items-center
                  gap-2
                  rounded-xl
                  border
                  border-[var(--border-color)]
                  px-4
                  py-2
                  hover:bg-[var(--card-hover)]
                "
              >

                <Copy size={18} />

                Copy

              </button>

              <button
                onClick={downloadReport}
                className="
                  flex
                  items-center
                  gap-2
                  rounded-xl
                  border
                  border-[var(--border-color)]
                  px-4
                  py-2
                  hover:bg-[var(--card-hover)]
                "
              >

                <Download size={18} />

                Download PDF

              </button>

            </div>

          </div>

          <div
            className="
              rounded-xl
              bg-[var(--app-bg)]
              p-6
              whitespace-pre-wrap
              leading-8
              text-[var(--primary-text)]
            "
          >

            {report}

          </div>

        </div>

      )}

    </MainLayout>

  );

}

export default LiteratureSurvey;