import { useState } from "react";
import { jsPDF } from "jspdf";
import {
  BrainCircuit,
  Copy,
  Download,
  Sparkles,
} from "lucide-react";

import MainLayout from "../layouts/MainLayout";

function ResearchGap() {

  const [loading, setLoading] = useState(false);
  const [report, setReport] = useState("");

  const generateResearchGap = async () => {

    setLoading(true);

    try {

      const response = await fetch(
        "http://127.0.0.1:5000/research-gap"
      );

      const data = await response.json();

      if (data.success) {

        setReport(data.research_gap);

      } else {

        alert(data.message || "Unable to generate report.");

      }

    } catch (error) {

      console.log(error);

      alert("Unable to connect to backend.");

    }

    setLoading(false);

  };

  const copyReport = () => {

    navigator.clipboard.writeText(report);

    alert("Research Gap copied successfully.");

  };

  const downloadReport = () => {

    if (!report) {

      alert("Please generate a report first.");
      return;

    }

    const pdf = new jsPDF({
      orientation: "portrait",
      unit: "mm",
      format: "a4",
    });

    // Title
    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(20);
    pdf.text("ResearchMind AI", 20, 20);

    // Subtitle
    pdf.setFontSize(14);
    pdf.text("Research Gap Report", 20, 30);

    // Date
    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(10);

    const today = new Date().toLocaleString();

    pdf.text(`Generated On: ${today}`, 20, 38);

    // Divider
    pdf.line(20, 42, 190, 42);

    // Report Content
    pdf.setFontSize(12);

    const lines = pdf.splitTextToSize(report, 170);

    pdf.text(lines, 20, 52);

    // Footer
    pdf.setFontSize(10);
    pdf.text(
      "Generated by ResearchMind AI",
      20,
      285
    );

    pdf.save("ResearchGapReport.pdf");

  };

  return (

    <MainLayout>

      {/* Header */}

      <div className="flex items-center gap-5">

        <div
          className="
            rounded-2xl
            bg-[var(--button-bg)]
            p-4
          "
        >

          <BrainCircuit
            size={38}
            className="text-[var(--button-text)]"
          />

        </div>

        <div>

          <h1 className="text-4xl font-bold text-[var(--primary-text)]">

            Research Gap Detection

          </h1>

          <p className="mt-2 text-[var(--secondary-text)]">

            Identify research gaps, common limitations,
            future opportunities and possible project ideas
            from uploaded research papers.

          </p>

        </div>

      </div>

      {/* Generate Button */}

      <div className="mt-10">

        <button
          onClick={generateResearchGap}
          disabled={loading}
          className="
            flex
            items-center
            gap-3
            rounded-xl
            bg-[var(--button-bg)]
            px-7
            py-3
            font-semibold
            text-[var(--button-text)]
            transition
            hover:opacity-90
            disabled:opacity-50
          "
        >

          <Sparkles size={18} />

          {loading
            ? "Generating Research Gap..."
            : "Generate Research Gap"}

        </button>

      </div>

      {/* Loading */}

      {loading && (

        <div
          className="
            mt-8
            rounded-2xl
            border
            border-[var(--border-color)]
            bg-[var(--card-bg)]
            p-8
          "
        >

          <p className="text-lg font-medium">

            AI is analyzing your research papers...

          </p>

          <p className="mt-3 text-[var(--secondary-text)]">

            Comparing methodologies, limitations,
            future opportunities and research ideas.

          </p>

        </div>

      )}

      {/* Report */}

      {!loading && report && (

        <div
          className="
            mt-10
            rounded-2xl
            border
            border-[var(--border-color)]
            bg-[var(--card-bg)]
            p-8
          "
        >

          <div className="mb-8 flex items-center justify-between">

            <div>

              <h2 className="text-2xl font-bold">

                AI Research Report

              </h2>

              <p className="mt-2 text-sm text-[var(--secondary-text)]">

                Generated from uploaded research papers.

              </p>

            </div>

            <div className="flex gap-3">

              <button
                onClick={copyReport}
                className="
                  flex
                  items-center
                  gap-2
                  rounded-xl
                  border
                  border-[var(--border-color)]
                  px-4
                  py-2
                  hover:bg-[var(--card-hover)]
                "
              >

                <Copy size={18} />

                Copy

              </button>

              <button
                onClick={downloadReport}
                className="
                  flex
                  items-center
                  gap-2
                  rounded-xl
                  border
                  border-[var(--border-color)]
                  px-4
                  py-2
                  hover:bg-[var(--card-hover)]
                "
              >

                <Download size={18} />

                Download PDF

              </button>

            </div>

          </div>

          <div
            className="
              rounded-xl
              bg-[var(--app-bg)]
              p-6
              whitespace-pre-wrap
              leading-8
              text-[var(--primary-text)]
            "
          >

            {report}

          </div>

        </div>

      )}

    </MainLayout>

  );

}

export default ResearchGap;